server:
    port: 8099

spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: jdbc:postgresql://localhost:5432/sample
        username: postgres
        password: root

    jpa:
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    devtools:
        remote:
            debug:
                enabled: false

liquibase:
    change-log: classpath:/config/liquibase/master.xml
    user: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/sample
    contexts: development, production
